services:
  web:
    image: sukhbhambra/svn-art-gallery:prod-v1.0.1
    container_name: svn-art-gallery-web-prod-v1.0.1-container
    build:
      context: .
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./css:/usr/share/nginx/html/css:ro
      - ./images:/usr/share/nginx/html/images:ro
      - ./js:/usr/share/nginx/html/js:ro
      - ./pages:/usr/share/nginx/html/pages:ro
